### PR TITLE
Ruy's interests, skills

### PR DESCRIPTION
**Pull request by ruy-jauregui**
My first contribution to this project

### CODE REVIEW

**Comment by ruy-jauregui** [comment]
interests

**Comment by mdavy86** [comment]
@ruyjau, you are going to have to resolve conflicts, in the [network diagram](https://github.com/biospectrabysequencing/BBS_Meeting_2015/network) you did not get your clone/fork [up to date](https://github.com/biospectrabysequencing/BBS_Meeting_2015/blob/master/github/fork_vs_clone.md#forking-and-keeping-up-to-date) with the upstream master repository, and you made a change based on commit 9be4c44.

The command line instructions github provides should fix it

```
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b ruyjau-ruyjau-patch-1 master
git pull https://github.com/ruyjau/BBS_Meeting_2015.git ruyjau-patch-1

Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff ruyjau-ruyjau-patch-1
git push origin master
```

See also [resolving a merge conflict](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/)

**Comment by ruy-jauregui** [comment]
I see! Ta!

**Comment by mdavy86** [comment]
Note too, I went onto other contributors forks (including your) and opened pull requests to push changes into upstream::master (not normal practice).

**Comment by mdavy86** [comment]
You will need to fetch commit efd4136 too

**Comment by ruy-jauregui** [comment]
When I try 
git push origin master
I get a forbidden access error:
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/ruyjau/BBS_Meeting_2015.git/info/refs

How do I fetch the specific commit efd4136?

**Comment by mdavy86** [comment]
@ruyjau, check your remotes, I have these currently defined, because I own my origin fork, I can push to it

**Note: This set has been updated - wrong repo!**

``` bash
git remote -v
origin  git@github.com:mdavy86/BBS_Meeting_2015.git (fetch)
origin  git@github.com:mdavy86/BBS_Meeting_2015.git (push)
ruyjau  git@github.com:ruyjau/BBS_Meeting_2015.git (fetch)
ruyjau  git@github.com:ruyjau/BBS_Meeting_2015.git (push)
upstream        https://github.com/biospectrabysequencing/BBS_Meeting_2015 (fetch)
upstream        https://github.com/biospectrabysequencing/BBS_Meeting_2015 (push)
```

**Comment by relshire** [comment]
@mdavy86, Playing the newb (rather being the newb), after checking the remotes, how does one _define_ a remote....

**Comment by mdavy86** [comment]
Good question. It is sort of covered [here](https://github.com/biospectrabysequencing/BBS_Meeting_2015/blob/990e64b7ee6d0e73c53ab0ec9d865f8854df25b8/github/fork_vs_clone.md#forking-and-keeping-up-to-date), but essentially we can configure any remote **name** with `git remote add`, `git remote rename`, `git remote rm` etc. The help page [git remote --help](https://git-scm.com/docs/git-remote.html) provides more detail.

It is also covered in the tutorial
[altassian tutorial topic syncing](https://www.atlassian.com/git/tutorials/syncing/)

The main point is that we can name remotes anything we like, but for consistency the convention 
- upstream = bbs repository
- origin = our own github _user_ fork

is being recommended. Usually we clone from **our** origin repository, in that case it would be

``` bash
## From a terminal
git clone git@github.com:mdavy86/BBS_Meeting_2015.git  ## Note own username in the url 
```

Cloning automatically defines a remote as `origin` from memory.

Now clones of a repository are just copies of a code base that are at different states, so you can clone from `origin` or `upstream`, redefine your remotes accordingly then synchronize content, and you are in the same position.

**Pull request merged**
